export const SHOW_NAV_SIDE_DRAWER = 'SHOW_NAV_SIDE_DRAWER';
export const CLOSE_NAV_SIDE_DRAWER = 'CLOSE_NAV_SIDE_DRAWER';

export const SET_BLOGS = 'SET_BLOGS';
export const FETCH_BLOGS_START = 'FETCH_BLOGS_START';
export const FETCH_BLOGS_FAILED = 'FETCH_BLOGS_FAILED';
export const FETCH_BLOG_START = 'FETCH_BLOG_START';
export const SET_BLOG = 'SET_BLOG';
export const FETCH_BLOG_FAILED = 'FETCH_BLOG_FAILED';